# Generated by Django 4.2.5 on 2023-09-14 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='web_companyX', verbose_name='upload_logo')),
                ('website_name', models.CharField(max_length=45, verbose_name='your website/project name:')),
                ('the_url', models.CharField(max_length=200, verbose_name='add web site domain')),
                ('posted_in', models.DateTimeField(auto_now_add=True)),
                ('website_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_url_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
