# Generated by Django 4.2.5 on 2023-09-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_owner',
            name='logo',
            field=models.ImageField(null=True, upload_to='web_companyX', verbose_name='upload_logo'),
        ),
        migrations.CreateModel(
            name='Tracking_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_track', models.DateTimeField(auto_now_add=True)),
                ('the_tracked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='tracker.website_owner')),
            ],
        ),
    ]
