# Generated by Django 4.2.5 on 2023-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_website_owner_logo_tracking_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_owner',
            name='my_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='website_owner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='web_companyX', verbose_name='upload_logo'),
        ),
    ]
